


class EnumInvoice:

    PARCEL_AWAIT_FOR_CONFIRM= 'PARCEL_AWAIT_FOR_CONFIRM'
    PARCEL_CANCEL = 'PARCEL_CANCEL'
    PARCEL_CONFIRM_BY_VENDOR = 'PARCEL_CONFIRM_BY_VENDOR'
    INVOICE_AWAIT_FOR_CONFIRM = 'INVOICE_AWAIT_FOR_CONFIRM'
    INVOICE_CANCEL = 'INVOICE_CANCEL'
    INVOICE_CONFIRM = 'INVOICE_CONFIRM'
    STATUS_DELIVERY='STATUS_DELIVERY'
    METHOD_POST_AMADAST='METHOD_POST_AMADAST'
    METHOOD_POST_TIPAX = 'METHOD_POST_TIPAX'
    PARCEL_SEND_BY_VENDOR='PARCEL_SEND_BY_VENDOR'
    METHOD_POST='METHOD_POST'
    CANCEL_BY_SYSTEM_TIMEOUT: str='CANCEL_BY_SYSTEM_TIMEOUT'
