


class EnumInvoice:
    PARCEL_AWAIT_FOR_CONFIRM= 'PARCEL_AWAIT_FOR_CONFIRM'
    PARCEL_CANCEL = 'PARCEL_CANCEL'
    PARCEL_CONFIRM = 'PARCEL_CONFIRM'
    INVOICE_AWAIT_FOR_CONFIRM = 'INVOICE_AWAIT_FOR_CONFIRM'
    INVOICE_CANCEL = 'INVOICE_CANCEL'
    INVOICE_CONFIRM = 'INVOICE_CONFIRM'
