


class EnumInvoice:
    PARCEL_AWAIT_FOR_CONFIRM= 'PARCEL_AWAIT_FOR_CONFIRM'
    PARCEL_CANCEL = 'PARCEL_CANCEL'
    PARCEL_CONFIRM = 'PARCEL_CONFIRM'
    INVOICE_AWAIT_FOR_CONFIRM = 'INVOICE_AWAIT_FOR_CONFIRM'
    INVOICE_CANCEL = 'INVOICE_CANCEL'
    INVOICE_CONFIRM = 'INVOICE_CONFIRM'
    STATUS_DELIVERY='STATUS_DELIVERY'
    METHOD_POST_AMADAST='METHOD_POST_AMADAST'
    METHOOD_POST_TIPAX = 'METHOD_POST_TIPAX'
    METHOD_POST='METHOD_POST'

