name: Continuous Deployment on Tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Deploy to Linux Server via SSH and Restart Service
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          echo "Starting production deployment for tag: ${{ github.ref_name }}"
          PROJECT_DIR="/home/amir/amirhossein/task5-production" 
          cd $PROJECT_DIR || exit 1 
          git fetch origin
          git checkout ${{ github.ref_name }}
          $PROJECT_DIR/.venv/bin/python3 -m pip install -r requirements.txt
          sudo systemctl restart task5-production.service           
          sudo systemctl status task5-production.service
          echo "Deployment finished. Service restarted."